// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WheelStrategy.Api.Data;

#nullable disable

namespace WheelStrategy.Api.Data.Migrations
{
    [DbContext(typeof(WheelStrategyDbContext))]
    [Migration("20260808160000_OrderJournal")]
    partial class OrderJournal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("WheelStrategy.Api.Models.HistoricalBar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adjustment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BarStart")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TradeCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("VWAP")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "BarStart")
                        .IsUnique();

                    b.ToTable("HistoricalBars");
                });

            modelBuilder.Entity("WheelStrategy.Api.Models.OrderJournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlpacaOrderId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrokerStatus")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeskState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilledQty")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LimitPrice")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Qty")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TerminalAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Underlying")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlpacaOrderId");

                    b.HasIndex("ClientOrderId")
                        .IsUnique();

                    b.HasIndex("Underlying", "UpdatedAt");

                    b.ToTable("OrderJournalEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
