// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WheelStrategy.Api.Data;

#nullable disable

namespace WheelStrategy.Api.Data.Migrations
{
    [DbContext(typeof(WheelStrategyDbContext))]
    [Migration("20260808170844_TradeOutcomes")]
    partial class TradeOutcomes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("WheelStrategy.Api.Models.HistoricalBar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adjustment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BarStart")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TradeCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("VWAP")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "BarStart")
                        .IsUnique();

                    b.ToTable("HistoricalBars");
                });

            modelBuilder.Entity("WheelStrategy.Api.Models.OrderJournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlpacaOrderId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrokerStatus")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeskState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilledQty")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LimitPrice")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Qty")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TerminalAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Underlying")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlpacaOrderId");

                    b.HasIndex("ClientOrderId")
                        .IsUnique();

                    b.HasIndex("Underlying", "UpdatedAt");

                    b.ToTable("OrderJournalEntries");
                });

            modelBuilder.Entity("WheelStrategy.Api.Models.TradeOutcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlpacaOrderId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AnomalyReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BidAtSubmit")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CohortKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionSnapshotJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Dte")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("EarningsInWindow")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("EmpiricalAssignmentProb")
                        .HasColumnType("REAL");

                    b.Property<double?>("EstPremium")
                        .HasColumnType("REAL");

                    b.Property<decimal?>("Fees")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FilledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilledAvgPrice")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilledQty")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Granularity")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("HmmRegime")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnomaly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("LimitPrice")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MidAtSubmit")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ModelStrike")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionRight")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutcomeLabel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PremiumCash")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Qty")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RealizedPnL")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SnappedStrike")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SpotAtSubmit")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuggestedLimit")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double?>("TargetDelta")
                        .HasColumnType("REAL");

                    b.Property<string>("Underlying")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WheelCycleId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("WheelSide")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrderId")
                        .IsUnique();

                    b.HasIndex("CohortKey");

                    b.HasIndex("OutcomeLabel");

                    b.HasIndex("WheelCycleId");

                    b.HasIndex("Underlying", "UpdatedAt");

                    b.ToTable("TradeOutcomes");
                });
#pragma warning restore 612, 618
        }
    }
}
